# Generated by Django 5.2.7 on 2025-11-19 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_choice_delete_vote'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='option',
            new_name='choice_text',
        ),
    ]
