# Generated by Django 5.2.7 on 2025-11-19 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_rename_option_choice_choice_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='created_at',
        ),
    ]
